//types de proyectos
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const CARGAR_NUEVO_PROYECTO = 'CARGAR_NUEVO_PROYECTO';
export const VALIDAR_INPUT = 'VALIDAR_INPUT';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO_ACTUAL = 'ELIMINAR_PROYECTO_ACTUAL';
//types de tareas
export const VALIDAR_INPUT_TAREAS = 'VALIDAR_INPUT_TAREAS';
export const OBTENER_TAREAS = 'OBTENER_TAREAS';
export const CARGAR_NUEVA_TAREA = 'CARGAR_NUEVA_TAREA';
export const MODIFICAR_ESTADO_TAREA = 'MODIFICAR_ESTADO_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const CAMBIAR_ESTADO_TAREA = 'CAMBIAR_ESTADO_TAREA ';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const EDITAR_TAREA = 'EDITAR_TAREA';
//types de alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
//types auth
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO ';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';